server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "changeme"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      http: true
    bufferDurationMs: 400
    frameBufferDurationMs: 1000
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
