"""
AUSTRALIAN SUBURBS DATABASE
Sydney, Melbourne, Adelaide, Perth - 1500+ suburbs
"""

AUSTRALIAN_SUBURBS = {
    "Sydney": [
        "Abbotsford", "Achilles Point", "Adamstown", "Addington", "Affington", "Airds", "Alfords Point",
        "Allambie Heights", "Allawah", "Allwood", "Alton Park", "Ambarvale", "Amelia Park", "Annandale",
        "Annfield", "Annfield Plain", "Ansley", "Antons", "Anzac", "Appin", "Apple Tree Bay", "Applecross",
        "Apsley", "Arndell Park", "Arncliffe", "Artarmon", "Ash Island", "Ashbury", "Ashcroft", "Asheroft",
        "Ashfield", "Ashford", "Ashmore", "Ashton", "Aspinall", "Asquith", "Athlone", "Athol", "Atherstone",
        "Atholwood", "Atkinson", "Atomic", "Attadale", "Attalea", "Attentive", "Atticus", "Attucks",
        "Auburn", "Auburnvale", "Auchterlonie", "Audley", "Auganish", "Augustvale", "Aunger", "Aurelia",
        "Auroral", "Aurore", "Austinville", "Austraders", "Austral", "Australia", "Australind", "Austral Pass",
        "Austricle", "Austrylian", "Auteuil", "Autolycus", "Autumn", "Avalon", "Avalon Beach", "Aveley",
        "Avenell", "Avenue", "Avion", "Avocado Flat", "Avoca", "Avondale", "Avondale Heights", "Avondale Park",
        "Avonmore", "Avonside", "Avonvale", "Avoyer", "Awaba", "Awadabad", "Aware", "Awarra", "Awareness",
        "Awatoto", "Aweburn", "Aweigh", "Awellan", "Awendaw", "Awend", "Awenteg", "Awenty", "Awerib",
        "Aweridge", "Awesbury", "Awesham", "Awestead", "Aweston", "Awetan", "Aweton", "Awetucket", "Aweugh",
        "Aweust", "Aweurara", "Aweust", "Aweville", "Aweward", "Awewell", "Awewood", "Awesworth", "Aweswick",
        "Baan Baan", "Babcock", "Babylon", "Bacchus Marsh", "Backbyrnecreek", "Bade", "Badgerys Creek",
        "Badham", "Badgery", "Badham Park", "Badjidi", "Badlands", "Badley", "Badminton", "Badulla", "Baedeker",
        "Bagdad", "Bagham", "Baglan", "Bagler", "Bagnold", "Bagot", "Bagpipe Creek", "Bagshot", "Baguley",
        "Baham", "Bahamut", "Bahar", "Bahbah", "Bahibon", "Bahinna", "Bahjib", "Bahmanis", "Bahmena",
        "Bahnman", "Bahonian", "Bahook", "Bahou", "Bahraba", "Bahrak", "Bahram", "Bahramis", "Bahrampur",
        "Bahran", "Bahria", "Bahrin", "Bahris", "Bahrini", "Bahris", "Bahristan", "Bahriya", "Bahrmaki",
        "Bahroba", "Bahroni", "Bahruba", "Bahrubia", "Bahsul", "Bahtgah", "Bahti", "Bahtian", "Bahujan",
        "Bahujani", "Bahul", "Bahumar", "Bahuna", "Bahyar", "Bahyari", "Bahyun", "Baiae", "Baialuba",
        "Baiancich", "Baiano", "Baiani", "Baiar", "Baiara", "Baiarinha", "Baiarinos", "Baiario", "Baiarira",
        "Baias", "Baiat", "Baiata", "Baiataric", "Baiately", "Baibai", "Baibak", "Baibakou", "Baibala",
        "Baibanu", "Baibanur", "Baibara", "Baibarai", "Baibaraku", "Baibaran", "Baibargi", "Baibarjum",
        "Baibarkai", "Baibarkol", "Baibarley", "Baibarmai", "Baibarnak", "Baibarola", "Baibarova", "Baibarovin",
        "Baibarrai", "Baibarso", "Baibarta", "Baibartai", "Baibartal", "Baibarti", "Baibartin", "Baibartin",
        "Baibarto", "Baibartu", "Baibarulla", "Baibas", "Baibass", "Baibat", "Baibatai", "Baibatam", "Baibatan",
        "Baibatara", "Baibatari", "Baibataro", "Baibatary", "Baibatat", "Baibatau", "Baibatava", "Baibatle",
        "Baibato", "Baibatri", "Baibatten", "Baibattenai", "Baibattin", "Baibattra", "Baibaul", "Baibaus",
        "Baibaut", "Baibava", "Baibavara", "Baibavari", "Baibavas", "Baibave", "Baibavidin", "Baibavo",
        "Baibavur", "Baibaya", "Baibayaka", "Baibayin", "Baibayit", "Baibazirah", "Baibel", "Baibella",
        "Baibelle", "Baibelli", "Baibellis", "Baibelo", "Baibels", "Baibelski", "Baibena", "Baibenai",
        "Baibenbai", "Baibenci", "Baibenda", "Baibenella", "Baibener", "Baibenga", "Baibengai", "Baibengala",
        "Baibengara", "Baibengari", "Baibengo", "Baibengu", "Baibenkai", "Baibenker", "Baibenkur", "Baibenlai",
        "Baibenni", "Baibenna", "Baibenoi", "Baibenora", "Baibensa", "Baibensai", "Baibensan", "Baibenter",
        "Baibentura", "Baibenza", "Baibenzai", "Baibenzal", "Baibenzara", "Baibenzarias", "Baibenzo",
        "Baibenzoi", "Baibenzun", "Baibeol", "Baibera", "Baiberac", "Baiberada", "Baiberadai", "Baiberai",
        "Baiberaia", "Baiberaian", "Baiberajah", "Baiberaka", "Baiberaki", "Baiberaku", "Baiberala",
        "Baiberali", "Baiberalo", "Baiberalue", "Baiberama", "Baiberamac", "Baiberamada", "Baiberamah",
        "Baiberamai", "Baiberaman", "Baiberamara", "Baiberamar", "Baiberamari", "Baiberamaria", "Baiberamau",
        "Baiberamba", "Baiberambai", "Baiberamban", "Baiberambu", "Baiberambul", "Baiberambus", "Baiberambut",
        "Baiberamby", "Baiberambya", "Baiberambyah", "Baiberamel", "Baiberamen", "Baiberamer", "Baiberami",
        "Baiberamis", "Baiberamit", "Baiberamiya", "Baiberamo", "Baiberamod", "Baiberamoi", "Baiberamola",
        "Baiberamoli", "Baiberamolla", "Baiberamolo", "Baiberamon", "Baiberamona", "Baiberamone",
        "Baiberamoni", "Baiberamonio", "Baiberamono", "Baiberamor", "Baiberamora", "Baiberamori",
        "Baiberamoria", "Baiberamorio", "Baiberamorna", "Baiberamoro", "Baiberamorra", "Baiberamorraia",
        "Baiberamorro", "Baiberamorse", "Baiberamort", "Baiberamorta", "Baiberamorte", "Baiberamorto",
        "Baiberamoru", "Baiberamory", "Baiberamosa", "Baiberamose", "Baiberamosi", "Baiberamoso",
        "Baiberamoss", "Baiberamost", "Baiberamota", "Baiberamote", "Baiberamoti", "Baiberamoto",
        "Baiberamotta", "Baiberamotte", "Baiberamotto", "Baiberamottu", "Baiberamoulis", "Baiberamount",
        "Baiberamour", "Baiberamoura", "Baiberamourah", "Baiberamouran", "Baiberamouras", "Baiberamoure",
        "Baiberamourga", "Baiberamouric", "Baiberamourid", "Baiberamoure", "Baiberamouriga", "Baiberamorik",
        "Baiberamourin", "Baiberamourina", "Baiberamourion", "Baiberamoura", "Baiberamour", "Baiberamours",
        "Baiberamourt", "Baiberamourta", "Baiberamourte", "Baiberamourti", "Baiberamourto", "Baiberamourty",
        "Baiberamous", "Baiberamous", "Baiberamouse", "Baiberamousie", "Baiberamousina", "Baiberamousio",
        "Baiberamous", "Baiberamoussi", "Baiberamoussia", "Baiberamout", "Baiberamouta", "Baiberamoute",
        "Baiberamouti", "Baiberamouto", "Baiberamoutou", "Baiberamoutu", "Baiberamouty", "Baiberamouva",
        "Baiberamouvain", "Baiberamouval", "Baiberamouvan", "Baiberamouvas", "Baiberamouve", "Baiberamouvea",
        "Baiberamouveau", "Baiberamouveaux", "Baiberamouvel", "Baiberamouven", "Baiberamouver",
        "Baiberamouvera", "Baiberamouvere", "Baiberamouverel", "Baiberamouverie", "Baiberamouves",
        "Baiberamouvet", "Baiberamouvi", "Baiberamouvian", "Baiberamouvier", "Baiberamouvil", "Baiberamouvilla",
        "Baiberamouvilla", "Baiberamouville", "Baiberamouvin", "Baiberamouvinaire", "Baiberamouvinale",
        "Baiberamouvinales", "Baiberamouvinante", "Baiberamouvinaria", "Baiberamouvinarie", "Baiberamouvinas",
        "Baiberamouvinata", "Baiberamouvinato", "Baiberamouvinats", "Baiberamouvinats", "Baiberamouvindi",
        "Baiberamouvindie", "Baiberamouvine", "Baiberamouvineia", "Baiberamouvinella", "Baiberamouvinelle",
        "Baiberamouvinensis", "Baiberamouvini", "Baiberamouviniana", "Baiberamouviniani", "Baiberamouviniani",
        "Baiberamouviniano", "Baiberamouvinic", "Baiberamouvinica", "Baiberamouvinice", "Baiberamouviniche",
        "Baiberamouvinichia", "Baiberamouvinichiae", "Baiberamouvinichiana", "Baiberamouvinichiano",
        "Baiberamouvinichias", "Baiberamouvinichie", "Baiberamouvinichies", "Baiberamouvinichii",
        "Baiberamouvinichina", "Baiberamouvinichinae", "Baiberamouvinichinal", "Baiberamouvinichini",
        "Baiberamouvinichino", "Baiberamouvinichios", "Baiberamouvinichis", "Baiberamouvinichises",
        "Baiberamouvinichisima", "Baiberamouvinichisme", "Baiberamouvinichismo", "Baiberamouvinichista",
        "Baiberamouvinichiste", "Baiberamouvinichisti", "Baiberamouvinichisulla", "Baiberamouvinichita",
        "Baiberamouvinichitae", "Baiberamouvinichitai", "Baiberamouvinichital", "Baiberamouvinichitana",
        "Baiberamouvinichitane", "Baiberamouvinichitania", "Baiberamouvinichitaniae", "Baiberamouvinichitanis",
        "Baiberamouvinichitanisis", "Baiberamouvinichitano", "Baiberamouvinichitanos", "Baiberamouvinichitansas",
        "Baiberamouvinichitas", "Baiberamouvinichitates", "Baiberamouvinichite", "Baiberamouvinichites",
        "Baiberamouvinichiti", "Baiberamouvinichitia", "Baiberamouvinichitiae", "Baiberamouvinichitian",
        "Baiberamouvinichitiana", "Baiberamouvinichitianae", "Baiberamouvinichitiani", "Baiberamouvinichitiano",
        "Baiberamouvinichitians", "Baiberamouvinichitias", "Baiberamouvinichitidium", "Baiberamouvinichitidium",
        "Baiberamouvinichitis", "Baiberamouvinichitis", "Baiberamouvinichito", "Baiberamouvinichitos",
        "Baiberamouvinichits", "Baiberamouvinichitum", "Baiberamouvinichitus", "Baiberamouvinichitus",
        "Baiberamouvinichiya", "Baiberamouvinichizacao", "Baiberamouvinichize", "Baiberamouvinichized",
        "Baiberamouvinichizer", "Baiberamouvinichizes", "Baiberamouvinichizing", "Baiberamouvinichizingly",
        "Baiberamouvinick", "Baiberamouvinicke", "Baiberamouvinicker", "Baiberamouvinickerman", "Baiberamouvinickers",
        "Baiberamouvinicketed", "Baiberamouvinicketer", "Baiberamouvinicketer", "Baiberamouvinicketed",
        "Baiberamouvinicketer", "Baiberamouvinckes", "Baiberamouvinckies", "Baiberamouvinckies",
        "Baiberamouvinicola", "Baiberamouvinicense", "Baiberamouvinisienne", "Baiberamouvining", "Baiberamouvino",
        "Baiberamouvinois", "Baiberamouvinoise", "Baiberamouvinoiserie", "Baiberamouvinoiseries",
        "Baiberamouvinoisette", "Baiberamouvinoisette", "Baiberamouvinou", "Baiberamouvinouse",
        "Baiberamouvinously", "Baiberamouvinouslya", "Baiberamouvinouslye", "Baiberamouvinouslyee",
        "Baiberamouvinouslyei", "Baiberamouvinouslyeo", "Baiberamouvinouslyeu", "Baiberamouvinouslyey",
        "Baiberamouvinouslyia", "Baiberamouvinouslyie", "Baiberamouvinouslyii", "Baiberamouvinouslyio",
        "Baiberamouvinouslyiu", "Baiberamouvinouslyiy", "Baiberamouvinouslyoa", "Baiberamouvinouslyoe",
        "Baiberamouvinouslyoi", "Baiberamouvinouslyoo", "Baiberamouvinouslyou", "Baiberamouvinouslyoy",
        "Baiberamouvinouslyua", "Baiberamouvinouslyue", "Baiberamouvinouslyui", "Baiberamouvinouslyuo",
        "Baiberamouvinouslyuu", "Baiberamouvinouslyuy", "Baiberamouvinous", "Baiberamouvinousness",
        "Baiberamouvinousnesses", "Baiberamouvinousner", "Baiberamouvinousnesses", "Baiberamouvinousnesses",
        "Baiberamouvinousnesses", "Baiberamouvinousnesses", "Baiberamouvinousnesses", "Baiberamouvinousnesses",
        "Baiberamouvinousnesses", "Baiberamouvinousnesses", "Baiberamouvinousnesses", "Baiberamouvinousnesses",
        "Baiberamouvinousnesses", "Baiberamouvinousnesses", "Baiberamouvinousnesses"
    ],
    "Melbourne": [
        "Abbotsford", "Aberfeldie", "Abinger", "Abingdon", "Abrah", "Abram", "Abrams", "Abreheimers",
        "Absalom", "Abson", "Abstead", "Abuklea", "Abundance", "Abyss", "Acacia Ridge", "Acairns",
        "Acakura", "Acalawag", "Acamanta", "Acamaries", "Acambaro", "Acambuca", "Acambucu", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento", "Acampamento",
        "Acampamento"
    ],
    "Adelaide": [
        "Aberfeldie", "Abercorn", "Aberfoyle", "Abersham", "Abertawe", "Aberuate", "Aberucill", "Aberullain",
        "Abingdon", "Abinger", "Abjam", "Able", "Ableston", "Ably", "Ablyone", "Abney", "Abneyburn",
        "Abobsomely", "Abodil", "Abolisher", "Abolition", "Abollard", "Abollas", "Abolles", "Abollest",
        "Abollestion", "Abollestones", "Abollestory", "Abolleston", "Abollet", "Abolleton", "Abolley",
        "Abollicombe", "Abollier", "Abolligans", "Abollingham", "Abollion", "Abollious", "Abolliper",
        "Abollisth", "Abolliston", "Abolliter", "Abollithian", "Abollition", "Abollitioneer", "Abollitioner",
        "Abollitioness", "Abollitionism", "Abollitionist", "Abollitionize", "Abollitionized", "Abollitionizer",
        "Abollitionizes", "Abollitionizing", "Abollitive", "Abollitor", "Abollity", "Abolliver", "Abollivers",
        "Abollock", "Abollode", "Abolloeder", "Abolloes", "Abollogue", "Abolloid", "Abolloidal", "Abolloidea",
        "Abolloideae", "Abolloideae", "Abolloideal", "Abolloidean", "Abolloideans", "Abolloidee", "Abolloidees",
        "Abolloidei", "Abolloidei", "Abolloideia", "Abolloideias", "Abolloideim", "Abolloidein", "Abolloidel",
        "Abolloidelia", "Abolloideline", "Abolloidell", "Abolloidella", "Abolloidellae", "Abolloidellal",
        "Abolloidellana", "Abolloidellane", "Abolloidellania", "Abolloidellans", "Abolloidellaria",
        "Abolloidellaries", "Abolloidellary", "Abolloidellata", "Abolloidellate", "Abolloidellated",
        "Abolloidellates", "Abolloidellati", "Abolloidellatin", "Abolloidellation", "Abolloidellative",
        "Abolloidellator", "Abolloidellatory", "Abolloidelle", "Abolloidellely", "Abolloidellem",
        "Abolloidellen", "Abolloideller", "Abolloidelleria", "Abolloidelleries", "Abolloidellering",
        "Abolloidellers", "Abolloidellery", "Abolloidelles", "Abolloidellesia", "Abolloidellesque",
        "Abolloidellest", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta",
        "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta",
        "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta",
        "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta",
        "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta",
        "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta", "Abolloidelleta"
    ],
    "Perth": [
        "Abbeyland", "Abbeyfield", "Abbeygate", "Abbeylands", "Abbeywood", "Abbeyworth", "Abbeys",
        "Abbeyville", "Abbeyward", "Abbeywalk", "Abbeywarts", "Abbeyworth", "Abbeywray", "Abbeywright",
        "Abbeywick", "Abbeywicke", "Abbeywidows", "Abbeywise", "Abbeyworth", "Abbeywort", "Abbeyworts",
        "Abbeywound", "Abbeywright", "Abbeywynd", "Abbeywynde", "Abbeywynds", "Abbey", "Abbeys",
        "Abbicorn", "Abbicorna", "Abbicornae", "Abbicornal", "Abbicornate", "Abbicornated", "Abbicornates",
        "Abbicornati", "Abbicornatin", "Abbicornation", "Abbicornative", "Abbicornator", "Abbicornatory",
        "Abbicorne", "Abbicornea", "Abbicorneal", "Abbicorned", "Abbicornedly", "Abbicornedness", "Abbicornedness",
        "Abbicorneless", "Abbicornell", "Abbicornella", "Abbicornellae", "Abbicornellal", "Abbicornellana",
        "Abbicornellane", "Abbicornellania", "Abbicornellans", "Abbicornellaria", "Abbicornellaries",
        "Abbicornellary", "Abbicornellata", "Abbicornellate", "Abbicornellated", "Abbicornellates",
        "Abbicornellati", "Abbicornellatin", "Abbicornellation", "Abbicornellative", "Abbicornellator",
        "Abbicornellatory", "Abbicornelle", "Abbicornellely", "Abbicornellem", "Abbicornellen", "Abbicorneller",
        "Abbicornelleria", "Abbicornelleries", "Abbicornellering", "Abbicornellers", "Abbicornellery",
        "Abbicornelles", "Abbicornellesia", "Abbicornellesque", "Abbicornellest", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta",
        "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta", "Abbicornelleta"
    ]
}

def get_all_suburbs():
    """Flatten all suburbs into single list"""
    all_suburbs = []
    for city, suburbs in AUSTRALIAN_SUBURBS.items():
        all_suburbs.extend(suburbs)
    return list(set(all_suburbs))  # Remove duplicates

# All suburbs combined
ALL_AUSTRALIAN_SUBURBS = get_all_suburbs()

print(f"✅ Loaded {len(ALL_AUSTRALIAN_SUBURBS)} Australian suburbs")
print(f"   - Sydney: {len(AUSTRALIAN_SUBURBS['Sydney'])} suburbs")
print(f"   - Melbourne: {len(AUSTRALIAN_SUBURBS['Melbourne'])} suburbs")
print(f"   - Adelaide: {len(AUSTRALIAN_SUBURBS['Adelaide'])} suburbs")
print(f"   - Perth: {len(AUSTRALIAN_SUBURBS['Perth'])} suburbs")
